# Generated by Django 4.2 on 2023-06-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techMarket', '0002_userqueston'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
